eureka:
  instance:
    prefer-ip-address: true #서비스간 통신 시 hostname 보다 ip 를 우선 사용 함
  client:
    register-with-eureka: true #자기 자신은 서비스로 등록하지 않는다.
    fetch-registry: true #마이크로서비스인스턴스 목록을 로컬에 캐시할 것인지
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 5555

# /actuator/routes 엔드포인트를 호출하면 서비스 경로들이 보이는데
# 스프링 2.0 부터는 변경됨 .
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
zuul:
  sensitiveHeaders: Cookie,Set-Cookie # zuul은 기본적으로 예민한 Header 정보인 Cookie,Set-Cookie,authorization 정보를 전송하지않음.
  # 위에 뜻은, Cookie,Set-Cookie만 전송 안한다는 뜻
  prefix : /api
  zuul.debug.request: true


#위와 같이 엔드포인트를 노출시켜줘야 한다.

#이거 밑에꺼 쓰면 집킨한테 전송이 안된다.. 왜 안되지? 아오..
#spring:
#  zipkin:
#    baseUrl: localhost:9411
