# docker-compose -f [docker-compose.yml] up
version: '2'
services:
#  eurekaserver:
#    image:   johncarnell/tmx-eurekasvr:chapter9
#    ports:
#      - "8761:8761"
  outstagram-login:
    image: outstagram-login:latest
    container_name : "outstagram-login"
    ports:
      - "13333:13333"

#    environment:
#      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#      EUREKASERVER_PORT: "8761"
#      ENCRYPT_KEY:       "IMSYMMETRIC"
  # zipkin:
  #   image: johncarnell/tmx-zipkinsvr:chapter9
  #   ports:
  #     - "9411:9411"
  #   environment:
  #     SERVER_PORT: "9411"
#  zuulserver:
#    image: johncarnell/tmx-zuulsvr:chapter9
#    ports:
#      - "5555:5555"
#    environment:
#      PROFILE: "default"
#      SERVER_PORT: "5555"
#      CONFIGSERVER_URI: "http://configserver:8888"
#      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#      ZIPKIN_URI: "http://zipkin:9411"
#      DATABASESERVER_PORT: "5432"
#      EUREKASERVER_PORT:   "8761"
#      CONFIGSERVER_PORT:   "8888"
#      ZIPKIN_PORT:         "9411"
#  database:
#    image: postgres:9.5
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=p0stgr@s
#      - POSTGRES_DB=eagle_eye_local
#  licensingservice:
#    image: johncarnell/tmx-licensing-service:chapter9
#    ports:
#      - "8080:8080"
#    environment:
#      PROFILE: "default"
#      SERVER_PORT: "8080"
#      CONFIGSERVER_URI: "http://configserver:8888"
#      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#      ZIPKIN_URI: "http://zipkin:9411"
#      KAFKASERVER_URI: "kafkaserver"
#      ZKSERVER_URI: "zookeeper"
#      DATABASESERVER_PORT: "5432"
#      EUREKASERVER_PORT:   "8761"
#      CONFIGSERVER_PORT:   "8888"
#      ZUULSERVER_PORT:     "5555"
#      KAFKASERVER_PORT:    "2181"
#      REDIS_PORT:          "6379"
#      ZIPKIN_PORT:         "9411"
#      ENCRYPT_KEY:       "IMSYMMETRIC"
#  organizationservice:
#    image: johncarnell/tmx-organization-service:chapter9
#    ports:
#      - "8085:8085"
#    environment:
#      PROFILE: "default"
#      SERVER_PORT: "8085"
#      CONFIGSERVER_URI: "http://configserver:8888"
#      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
#      ZIPKIN_URI: "http://zipkin:9411"
#      KAFKASERVER_URI: "kafkaserver"
#      ZKSERVER_URI: "zookeeper"
#      DATABASESERVER_PORT: "5432"
#      EUREKASERVER_PORT:   "8761"
#      CONFIGSERVER_PORT:   "8888"
#      ZUULSERVER_PORT:     "5555"
#      KAFKASERVER_PORT:    "2181"
#      ZIPKIN_PORT:         "9411"
#      ENCRYPT_KEY:       "IMSYMMETRIC"
#  redis:
#    image: redis:alpine
#    ports:
#      - 6379:6379
#  # kafkaserver:
#  #   image: wurstmeister/kafka
#  #   ports:
#  #     - 2181:2181
#  #     - 9092:9092
#
#  zookeeper:
#    image: wurstmeister/zookeeper
#    container_name: zookeeper
#    restart: always
#    ports:
#      - 2181:2181
#
#  kafkaserver:
#    image: wurstmeister/kafka
#    container_name: kafka
#    restart: always
#    ports:
#      - 9092:9092
#    depends_on:
#      - zookeeper
#    links:
#      - zookeeper:zookeeper
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#
#  #  This is the openzipkin server.
#  zipkin:
#    image: openzipkin/zipkin
#    ports:
#      - 9411:9411
#  #Attention:  Replace the value in the “command” attribute with the value supplied to you from Papertrail
#  logspout:
#    image: gliderlabs/logspout
#    command: syslog://logs7.papertrailapp.com:27040
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock