---
ribbon:
  eureka:
    enabled: true
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true #서비스간 통신 시 hostname 보다 ip 를 우선 사용 함
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


server:
  port: 13333

signing :
  #sha256(outstagram)
  key : F79FEA4B2DFB766FE645F05853069FF883271ABD1BCE56C46CEDCA1F9723593C

spring:
  cloud:
    # stream.bindings는 서비스 스프링 클라우드 스트림의 메세지 브로커에 발행하려는 구성의 시작점이다.
    stream:
      bindings:
        output:
          destination: loginChangeTopic
          contentType: application/json
      kafka:
        binder:
          zk-nodes: localhost
          brokers: localhost

  profiles: default
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  #  main:
  #    web-application-type: none # 웹 어플리케이션이면 이 프로퍼티를 써줘야한다.
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/outstagram?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: outstagram
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root : debug
    com :
      project :
        outstagram : debug



security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user

---
ribbon:
  eureka:
    enabled: true
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true #서비스간 통신 시 hostname 보다 ip 를 우선 사용 함
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


server:
  port: 13333

signing :
  #sha256(outstagram)
  key : F79FEA4B2DFB766FE645F05853069FF883271ABD1BCE56C46CEDCA1F9723593C

spring:
  cloud:
    # stream.bindings는 서비스 스프링 클라우드 스트림의 메세지 브로커에 발행하려는 구성의 시작점이다.
    stream:
      bindings:
        output:
          destination: loginChangeTopic
          contentType: application/json
      kafka:
        binder:
          zk-nodes: localhost
          brokers: localhost

  profiles: docker
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  #  main:
  #    web-application-type: none # 웹 어플리케이션이면 이 프로퍼티를 써줘야한다.
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
#으.. 망할 도커자식!!
  #
  #The ports mapping in your docker-compose.yml is only relevant for the host,
   # so you'll be able to connect to your DB through localhost:3308.
    #But inside your other docker-compose containers (that is, the compose default network),
    #you'd have to use workaround-mysql:3306.
    #https://stackoverflow.com/questions/56429995/spring-boot-docker-cannot-connect-to-mysql-connection-refused-createcommunica/56431451#56431451
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/outstagram?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    com :
      project :
        outstagram : debug



security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user
